// weather_provider.dart

import 'dart:convert';
import 'package:flutter/foundation.dart';
import 'package:krishi_connect/repo/model/weather.dart';

class WeatherProvider with ChangeNotifier {
  WeatherFutureResponse? _weather;
  bool _loading = false;
  String? _error;

  WeatherFutureResponse? get weather => _weather;
  bool get loading => _loading;
  String? get error => _error;

  Future<void> fetchFutureWeather({
    required String location,
    required String date, // yyyy-MM-dd
  }) async {
    _loading = true;
    notifyListeners();

    try {
      /// 🔁 Replace `mockWeatherJson` with API response when moving to production
      final Map<String, dynamic> jsonData = jsonDecode(
        mockWeatherJson,
      ); // <-- ONE LINE TO SWITCH

      _weather = WeatherFutureResponse.fromJson(jsonData);
      _error = null;
    } catch (e) {
      _error = e.toString();
    } finally {
      _loading = false;
      notifyListeners();
    }
  }
}

const String mockWeatherJson = '''
{
  "location": {
    "name": "Kopargaon",
    "region": "Maharashtra",
    "country": "India",
    "lat": 19.8833,
    "lon": 74.4833,
    "tz_id": "Asia/Kolkata",
    "localtime_epoch": 1766303792,
    "localtime": "2025-12-21 13:26"
  },
  "forecast": {
    "forecastday": [
      {
        "date": "2026-01-15",
        "date_epoch": 1768435200,
        "day": {
          "maxtemp_c": 29.5,
          "maxtemp_f": 85.1,
          "mintemp_c": 16.2,
          "mintemp_f": 61.2,
          "avgtemp_c": 22.7,
          "avgtemp_f": 72.9,
          "maxwind_mph": 8.5,
          "maxwind_kph": 13.7,
          "totalprecip_mm": 0,
          "totalprecip_in": 0,
          "avgvis_km": 10,
          "avgvis_miles": 6,
          "avghumidity": 39,
          "condition": {
            "text": "Sunny",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
            "code": 1000
          },
          "uv": 6
        },
        "astro": {
          "sunrise": "07:10 AM",
          "sunset": "06:13 PM",
          "moonrise": "04:14 AM",
          "moonset": "03:09 PM",
          "moon_phase": "Waning Crescent",
          "moon_illumination": 15
        },
        "hour": [
          {
            "time_epoch": 1768422600,
            "time": "2026-01-15 02:00",
            "temp_c": 17.9,
            "temp_f": 64.2,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 4.7,
            "wind_kph": 7.6,
            "wind_degree": 176,
            "wind_dir": "S",
            "pressure_mb": 1014,
            "pressure_in": 29.94,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 48,
            "cloud": 12,
            "feelslike_c": 17.9,
            "feelslike_f": 64.2,
            "windchill_c": 17.9,
            "windchill_f": 64.2,
            "heatindex_c": 18.2,
            "heatindex_f": 64.8,
            "dewpoint_c": 8.7,
            "dewpoint_f": 47.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 7.8,
            "gust_kph": 12.6,
            "uv": 0
          },
          {
            "time_epoch": 1768426200,
            "time": "2026-01-15 03:00",
            "temp_c": 17.4,
            "temp_f": 63.3,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 4.7,
            "wind_kph": 7.6,
            "wind_degree": 145,
            "wind_dir": "SE",
            "pressure_mb": 1014,
            "pressure_in": 29.94,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 49,
            "cloud": 12,
            "feelslike_c": 17.4,
            "feelslike_f": 63.3,
            "windchill_c": 17.4,
            "windchill_f": 63.3,
            "heatindex_c": 17.7,
            "heatindex_f": 63.9,
            "dewpoint_c": 8.2,
            "dewpoint_f": 46.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8.1,
            "gust_kph": 13,
            "uv": 0
          },
          {
            "time_epoch": 1768433400,
            "time": "2026-01-15 05:00",
            "temp_c": 17,
            "temp_f": 62.6,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 4.9,
            "wind_kph": 7.9,
            "wind_degree": 120,
            "wind_dir": "ESE",
            "pressure_mb": 1015,
            "pressure_in": 29.97,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 46,
            "cloud": 10,
            "feelslike_c": 17,
            "feelslike_f": 62.6,
            "windchill_c": 17,
            "windchill_f": 62.6,
            "heatindex_c": 17,
            "heatindex_f": 62.6,
            "dewpoint_c": 9.3,
            "dewpoint_f": 48.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 7.2,
            "gust_kph": 11.5,
            "uv": 0
          },
          {
            "time_epoch": 1768451400,
            "time": "2026-01-15 10:00",
            "temp_c": 24.5,
            "temp_f": 76.1,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 5.8,
            "wind_kph": 9.4,
            "wind_degree": 120,
            "wind_dir": "ESE",
            "pressure_mb": 1016,
            "pressure_in": 30,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 32,
            "cloud": 6,
            "feelslike_c": 24.9,
            "feelslike_f": 76.8,
            "windchill_c": 24.5,
            "windchill_f": 76.1,
            "heatindex_c": 24.9,
            "heatindex_f": 76.8,
            "dewpoint_c": 9.8,
            "dewpoint_f": 49.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.3,
            "gust_kph": 16.6,
            "uv": 0
          },
          {
            "time_epoch": 1768455000,
            "time": "2026-01-15 11:00",
            "temp_c": 26.5,
            "temp_f": 79.7,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 5.8,
            "wind_kph": 9.4,
            "wind_degree": 137,
            "wind_dir": "SE",
            "pressure_mb": 1015,
            "pressure_in": 29.98,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 30,
            "cloud": 6,
            "feelslike_c": 26,
            "feelslike_f": 78.8,
            "windchill_c": 26.5,
            "windchill_f": 79.7,
            "heatindex_c": 26,
            "heatindex_f": 78.8,
            "dewpoint_c": 9.5,
            "dewpoint_f": 49.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11.6,
            "gust_kph": 18.7,
            "uv": 0
          },
          {
            "time_epoch": 1768465800,
            "time": "2026-01-15 14:00",
            "temp_c": 29.2,
            "temp_f": 84.6,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 4.9,
            "wind_kph": 7.9,
            "wind_degree": 169,
            "wind_dir": "S",
            "pressure_mb": 1012,
            "pressure_in": 29.88,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 28,
            "cloud": 12,
            "feelslike_c": 28,
            "feelslike_f": 82.4,
            "windchill_c": 29.2,
            "windchill_f": 84.6,
            "heatindex_c": 28,
            "heatindex_f": 82.4,
            "dewpoint_c": 9.5,
            "dewpoint_f": 49.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11,
            "gust_kph": 17.6,
            "uv": 0
          },
          {
            "time_epoch": 1768473000,
            "time": "2026-01-15 16:00",
            "temp_c": 28.2,
            "temp_f": 82.8,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 4.5,
            "wind_kph": 7.2,
            "wind_degree": 162,
            "wind_dir": "SSE",
            "pressure_mb": 1012,
            "pressure_in": 29.88,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 31,
            "cloud": 14,
            "feelslike_c": 27.3,
            "feelslike_f": 81.1,
            "windchill_c": 28.2,
            "windchill_f": 82.8,
            "heatindex_c": 27.3,
            "heatindex_f": 81.1,
            "dewpoint_c": 9.4,
            "dewpoint_f": 48.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8.9,
            "gust_kph": 14.4,
            "uv": 0
          },
          {
            "time_epoch": 1768483800,
            "time": "2026-01-15 19:00",
            "temp_c": 23.5,
            "temp_f": 74.3,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 5.8,
            "wind_kph": 9.4,
            "wind_degree": 176,
            "wind_dir": "S",
            "pressure_mb": 1014,
            "pressure_in": 29.93,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 38,
            "cloud": 12,
            "feelslike_c": 24.5,
            "feelslike_f": 76.1,
            "windchill_c": 23.5,
            "windchill_f": 74.3,
            "heatindex_c": 24.5,
            "heatindex_f": 76.1,
            "dewpoint_c": 9.3,
            "dewpoint_f": 48.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.1,
            "gust_kph": 16.2,
            "uv": 0
          },
          {
            "time_epoch": 1768498200,
            "time": "2026-01-15 23:00",
            "temp_c": 19.7,
            "temp_f": 67.5,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 6.3,
            "wind_kph": 10.1,
            "wind_degree": 207,
            "wind_dir": "SSW",
            "pressure_mb": 1014,
            "pressure_in": 29.95,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 46,
            "cloud": 8,
            "feelslike_c": 19.7,
            "feelslike_f": 67.5,
            "windchill_c": 19.7,
            "windchill_f": 67.5,
            "heatindex_c": 20.2,
            "heatindex_f": 68.4,
            "dewpoint_c": 9,
            "dewpoint_f": 48.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11,
            "gust_kph": 17.6,
            "uv": 0
          },
          {
            "time_epoch": 1768415400,
            "time": "2026-01-15 00:00",
            "temp_c": 19.4,
            "temp_f": 66.9,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 5.4,
            "wind_kph": 8.6,
            "wind_degree": 201,
            "wind_dir": "SSW",
            "pressure_mb": 1014,
            "pressure_in": 29.95,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 46,
            "cloud": 11,
            "feelslike_c": 19.4,
            "feelslike_f": 66.9,
            "windchill_c": 19.4,
            "windchill_f": 66.9,
            "heatindex_c": 19.7,
            "heatindex_f": 67.5,
            "dewpoint_c": 8.1,
            "dewpoint_f": 46.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.6,
            "gust_kph": 15.5,
            "uv": 0
          },
          {
            "time_epoch": 1768437000,
            "time": "2026-01-15 06:00",
            "temp_c": 16.9,
            "temp_f": 62.4,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 4.9,
            "wind_kph": 7.9,
            "wind_degree": 107,
            "wind_dir": "ESE",
            "pressure_mb": 1015,
            "pressure_in": 29.98,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 45,
            "cloud": 10,
            "feelslike_c": 16.8,
            "feelslike_f": 62.2,
            "windchill_c": 16.8,
            "windchill_f": 62.2,
            "heatindex_c": 16.9,
            "heatindex_f": 62.4,
            "dewpoint_c": 9.4,
            "dewpoint_f": 48.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 6.9,
            "gust_kph": 11.2,
            "uv": 0
          },
          {
            "time_epoch": 1768440600,
            "time": "2026-01-15 07:00",
            "temp_c": 16.7,
            "temp_f": 62.1,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 5.1,
            "wind_kph": 8.3,
            "wind_degree": 112,
            "wind_dir": "ESE",
            "pressure_mb": 1016,
            "pressure_in": 29.99,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 42,
            "cloud": 8,
            "feelslike_c": 16.6,
            "feelslike_f": 61.9,
            "windchill_c": 16.6,
            "windchill_f": 61.9,
            "heatindex_c": 16.7,
            "heatindex_f": 62.1,
            "dewpoint_c": 10,
            "dewpoint_f": 50,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 6.9,
            "gust_kph": 11.2,
            "uv": 0
          },
          {
            "time_epoch": 1768458600,
            "time": "2026-01-15 12:00",
            "temp_c": 27.8,
            "temp_f": 82,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 5.8,
            "wind_kph": 9.4,
            "wind_degree": 173,
            "wind_dir": "S",
            "pressure_mb": 1014,
            "pressure_in": 29.94,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 28,
            "cloud": 7,
            "feelslike_c": 26.9,
            "feelslike_f": 80.4,
            "windchill_c": 27.8,
            "windchill_f": 82,
            "heatindex_c": 26.9,
            "heatindex_f": 80.4,
            "dewpoint_c": 9.6,
            "dewpoint_f": 49.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11.9,
            "gust_kph": 19.1,
            "uv": 0
          },
          {
            "time_epoch": 1768462200,
            "time": "2026-01-15 13:00",
            "temp_c": 28.7,
            "temp_f": 83.7,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 5.6,
            "wind_kph": 9,
            "wind_degree": 169,
            "wind_dir": "S",
            "pressure_mb": 1013,
            "pressure_in": 29.91,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 28,
            "cloud": 9,
            "feelslike_c": 27.6,
            "feelslike_f": 81.7,
            "windchill_c": 28.7,
            "windchill_f": 83.7,
            "heatindex_c": 27.6,
            "heatindex_f": 81.7,
            "dewpoint_c": 9.3,
            "dewpoint_f": 48.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11.6,
            "gust_kph": 18.7,
            "uv": 0
          },
          {
            "time_epoch": 1768469400,
            "time": "2026-01-15 15:00",
            "temp_c": 29.2,
            "temp_f": 84.6,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 4.5,
            "wind_kph": 7.2,
            "wind_degree": 170,
            "wind_dir": "S",
            "pressure_mb": 1012,
            "pressure_in": 29.87,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 29,
            "cloud": 14,
            "feelslike_c": 28.1,
            "feelslike_f": 82.6,
            "windchill_c": 29.2,
            "windchill_f": 84.6,
            "heatindex_c": 28.1,
            "heatindex_f": 82.6,
            "dewpoint_c": 9.8,
            "dewpoint_f": 49.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.6,
            "gust_kph": 15.5,
            "uv": 0
          },
          {
            "time_epoch": 1768476600,
            "time": "2026-01-15 17:00",
            "temp_c": 26.9,
            "temp_f": 80.4,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 4.5,
            "wind_kph": 7.2,
            "wind_degree": 155,
            "wind_dir": "SSE",
            "pressure_mb": 1013,
            "pressure_in": 29.9,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 34,
            "cloud": 14,
            "feelslike_c": 26.5,
            "feelslike_f": 79.7,
            "windchill_c": 26.9,
            "windchill_f": 80.4,
            "heatindex_c": 26.5,
            "heatindex_f": 79.7,
            "dewpoint_c": 9.4,
            "dewpoint_f": 48.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8.1,
            "gust_kph": 13,
            "uv": 0
          },
          {
            "time_epoch": 1768480200,
            "time": "2026-01-15 18:00",
            "temp_c": 24.9,
            "temp_f": 76.8,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 4.9,
            "wind_kph": 7.9,
            "wind_degree": 149,
            "wind_dir": "SSE",
            "pressure_mb": 1013,
            "pressure_in": 29.92,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 37,
            "cloud": 14,
            "feelslike_c": 25.3,
            "feelslike_f": 77.5,
            "windchill_c": 24.9,
            "windchill_f": 76.8,
            "heatindex_c": 25.3,
            "heatindex_f": 77.5,
            "dewpoint_c": 9.6,
            "dewpoint_f": 49.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 7.8,
            "gust_kph": 12.6,
            "uv": 0
          },
          {
            "time_epoch": 1768491000,
            "time": "2026-01-15 21:00",
            "temp_c": 21.4,
            "temp_f": 70.5,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 7.4,
            "wind_kph": 11.9,
            "wind_degree": 226,
            "wind_dir": "SW",
            "pressure_mb": 1014,
            "pressure_in": 29.96,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 42,
            "cloud": 8,
            "feelslike_c": 21.4,
            "feelslike_f": 70.5,
            "windchill_c": 21.4,
            "windchill_f": 70.5,
            "heatindex_c": 22,
            "heatindex_f": 71.6,
            "dewpoint_c": 8.7,
            "dewpoint_f": 47.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 12.1,
            "gust_kph": 19.4,
            "uv": 0
          },
          {
            "time_epoch": 1768494600,
            "time": "2026-01-15 22:00",
            "temp_c": 20.4,
            "temp_f": 68.7,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 6.7,
            "wind_kph": 10.8,
            "wind_degree": 216,
            "wind_dir": "SW",
            "pressure_mb": 1014,
            "pressure_in": 29.95,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 44,
            "cloud": 8,
            "feelslike_c": 20.4,
            "feelslike_f": 68.7,
            "windchill_c": 20.4,
            "windchill_f": 68.7,
            "heatindex_c": 20.9,
            "heatindex_f": 69.6,
            "dewpoint_c": 8.9,
            "dewpoint_f": 48,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11.6,
            "gust_kph": 18.7,
            "uv": 0
          },
          {
            "time_epoch": 1768419000,
            "time": "2026-01-15 01:00",
            "temp_c": 18.5,
            "temp_f": 65.3,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 5.1,
            "wind_kph": 8.3,
            "wind_degree": 187,
            "wind_dir": "S",
            "pressure_mb": 1014,
            "pressure_in": 29.95,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 47,
            "cloud": 11,
            "feelslike_c": 18.5,
            "feelslike_f": 65.3,
            "windchill_c": 18.5,
            "windchill_f": 65.3,
            "heatindex_c": 19,
            "heatindex_f": 66.2,
            "dewpoint_c": 8.7,
            "dewpoint_f": 47.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8.5,
            "gust_kph": 13.7,
            "uv": 0
          },
          {
            "time_epoch": 1768429800,
            "time": "2026-01-15 04:00",
            "temp_c": 17.2,
            "temp_f": 63,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 4.9,
            "wind_kph": 7.9,
            "wind_degree": 133,
            "wind_dir": "SE",
            "pressure_mb": 1014,
            "pressure_in": 29.95,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 48,
            "cloud": 11,
            "feelslike_c": 17.1,
            "feelslike_f": 62.8,
            "windchill_c": 17.1,
            "windchill_f": 62.8,
            "heatindex_c": 17.3,
            "heatindex_f": 63.1,
            "dewpoint_c": 8.9,
            "dewpoint_f": 48,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 7.2,
            "gust_kph": 11.5,
            "uv": 0
          },
          {
            "time_epoch": 1768444200,
            "time": "2026-01-15 08:00",
            "temp_c": 19,
            "temp_f": 66.2,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 5.1,
            "wind_kph": 8.3,
            "wind_degree": 117,
            "wind_dir": "ESE",
            "pressure_mb": 1016,
            "pressure_in": 29.99,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 38,
            "cloud": 6,
            "feelslike_c": 19,
            "feelslike_f": 66.2,
            "windchill_c": 19,
            "windchill_f": 66.2,
            "heatindex_c": 19.7,
            "heatindex_f": 67.5,
            "dewpoint_c": 10.7,
            "dewpoint_f": 51.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 7.6,
            "gust_kph": 12.2,
            "uv": 0
          },
          {
            "time_epoch": 1768447800,
            "time": "2026-01-15 09:00",
            "temp_c": 22.1,
            "temp_f": 71.8,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 5.4,
            "wind_kph": 8.6,
            "wind_degree": 102,
            "wind_dir": "ESE",
            "pressure_mb": 1016,
            "pressure_in": 30.01,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 35,
            "cloud": 5,
            "feelslike_c": 23,
            "feelslike_f": 73.4,
            "windchill_c": 22.1,
            "windchill_f": 71.8,
            "heatindex_c": 23,
            "heatindex_f": 73.4,
            "dewpoint_c": 10.1,
            "dewpoint_f": 50.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8.5,
            "gust_kph": 13.7,
            "uv": 0
          },
          {
            "time_epoch": 1768487400,
            "time": "2026-01-15 20:00",
            "temp_c": 22.3,
            "temp_f": 72.1,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 6.5,
            "wind_kph": 10.4,
            "wind_degree": 201,
            "wind_dir": "SSW",
            "pressure_mb": 1014,
            "pressure_in": 29.94,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 40,
            "cloud": 10,
            "feelslike_c": 23.4,
            "feelslike_f": 74.1,
            "windchill_c": 22.3,
            "windchill_f": 72.1,
            "heatindex_c": 23.4,
            "heatindex_f": 74.1,
            "dewpoint_c": 8.7,
            "dewpoint_f": 47.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11.2,
            "gust_kph": 18,
            "uv": 0
          }
        ]
      }
    ]
  }
}
''';
